### ISSUE TITLE
Loader template changes

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/TomoHub#5]
There were some changes in the httomo loader recently. The template now looks like this:
```
- method: standard_tomo
  module_path: httomo.data.hdf.loaders
  parameters:
    data_path: auto
    image_key_path: auto
    rotation_angles: auto
    preview:
      detector_x:   # horizontal data previewing/cropping.
        # when null, the full data dimension is used, i.e., no previewing
        start: null
        stop: null
      detector_y:   # vertical data previewing/cropping.
        # when null, the full data dimension is used, i.e., no previewing
        start: null
        stop: null
    darks: null
    flats: null
```

The `auto` field is by default now for paths, so you can add this as a default choice. It would be nice to generate the preview, darks and flats in the same way, even if they are not given by the user. So they are null/None, so we keep the structure similar as in the template. 
The last bit is not crucial, but if it is not difficult then it would be nice to have.
Thanks
